### ISSUE TITLE
"sweet" name confusion

### ISSUE THREAD

**Issue by FranklinChen** [vpj/sweet#1]
Hi, just letting you know that I got confused when I saw a reference to this project, because there is already a "sweet.js": http://sweetjs.org/

**Comment by vpj** [comment]
Thinking of renaming it to guava.js. WTYT?

**Comment by FranklinChen** [comment]
I don't know. I think names are just hard these days. Guava is a popular Java library!

**Comment by vpj** [comment]
Moved to https://github.com/vpj/weya
